import { createUseStyles } from 'react-jss';

export const Styles = createUseStyles({
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    height: '100vh',
    background: 'rgba(29,161,242,0.10)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1200,
  },
  modalContent: {
    background: '#fff',
    borderRadius: 24,
    boxShadow: '0 8px 32px rgba(29,161,242,0.18)',
    padding: '2.5rem 2rem 2rem 2rem',
    minWidth: 340,
    maxWidth: 420,
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
    position: 'relative',
  },
  header: {
    fontSize: '1.5rem',
    fontWeight: 700,
    color: '#1da1f2',
    marginBottom: '0.5rem',
    textAlign: 'center',
    letterSpacing: '0.5px',
  },
  closeButton: {
    position: 'absolute',
    top: 18,
    right: 18,
    background: 'transparent',
    border: 'none',
    color: '#657786',
    fontSize: '1.5rem',
    cursor: 'pointer',
    transition: 'color 0.18s',
    '&:hover': {
      color: '#1da1f2',
    },
    '&:focus-visible': {
      outline: '2px solid #1da1f2',
      outlineOffset: '2px',
    },
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.25rem',
  },
  actions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '1rem',
    marginTop: '1rem',
  },
    label: {
    fontWeight: 500,
    color: '#14171a',
    marginBottom: '0.25rem',
    display: 'flex',
    flexDirection: 'column',
    fontSize: '1rem',
    letterSpacing: '0.01em',
  },
  input: {
    border: '1.5px solid #e6ecf0',
    borderRadius: 16,
    padding: '0.5rem 1rem',
    fontSize: '1.05rem',
    color: '#14171a',
    marginTop: '0.25rem',
    outline: 'none',
    transition: 'border 0.18s, box-shadow 0.18s',
    background: '#fff',
    fontWeight: 500,
    '&:focus': {
      border: '1.5px solid #1da1f2',
      boxShadow: '0 2px 8px rgba(29,161,242,0.10)',
    },
    '&::placeholder': {
      color: '#657786',
      opacity: 1,
    },
  },
  error: {
    color: '#d63031',
    fontSize: '0.95rem',
    marginTop: '0.25rem',
    fontWeight: 500,
    letterSpacing: '0.01em',
    lineHeight: 1.3,
  },
})