import { createUseStyles } from 'react-jss';

export const useKibEditModalStyles = createUseStyles({
  form: {
    border: '1px solid #e0e0e0',
    borderRadius: 18,
    padding: 28,
    background: '#fff',
    boxShadow: '0 4px 24px rgba(9,132,227,0.13)',
    maxWidth: 540,
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: 18,
    margin: '0 auto',
  },
  label: {
    display: 'flex',
    flexDirection: 'column',
    fontWeight: 500,
    color: '#2d3436',
    fontSize: 15,
    marginBottom: 6,
    gap: 6,
  },
  input: {
    border: '1px solid #dfe6e9',
    borderRadius: 8,
    padding: '0.5rem 0.8rem',
    fontSize: 15,
    marginTop: 4,
    background: '#fafbfc',
    color: '#2d3436',
    outline: 'none',
    transition: 'border 0.2s',
    '&:focus': {
      border: '1.5px solid #0984e3',
      background: '#fff',
    },
    '&:disabled': {
      background: '#f0f0f0',
      color: '#b2bec3',
    },
  },
  textarea: {
    extend: 'input',
    minHeight: 60,
    resize: 'vertical',
  },
  error: {
    color: '#d63031',
    fontSize: 13,
    marginTop: 2,
    fontWeight: 400,
  },
  button: {
    alignSelf: 'flex-end',
    padding: '0.5rem 1.5rem',
    background: 'linear-gradient(90deg, #00b894 0%, #00cec9 100%)',
    border: 'none',
    borderRadius: 20,
    fontSize: 16,
    color: '#fff',
    fontWeight: 600,
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(0,184,148,0.10)',
    transition: 'background 0.2s, box-shadow 0.2s, transform 0.1s',
    marginTop: 10,
    '&:hover': {
      background: 'linear-gradient(90deg, #00cec9 0%, #00b894 100%)',
      boxShadow: '0 4px 16px rgba(0,184,148,0.15)',
      transform: 'translateY(-2px) scale(1.03)',
    },
    '&:active': {
      background: '#00b894',
      boxShadow: '0 2px 4px rgba(0,184,148,0.08)',
      transform: 'scale(0.98)',
    },
    '&:focus-visible': {
      outline: '2px solid #00b894',
      outlineOffset: '2px',
    },
  },
    footer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 18,
    paddingTop: 12,
    borderTop: '1px solid #e0e0e0',
    color: '#636e72',
    fontSize: 14,
    gap: 16,
  },
  likes: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontWeight: 500,
    color: '#0984e3',
  },
  created: {
    fontStyle: 'italic',
    color: '#636e72',
    fontSize: 13,
  },
});